# Generated by Django 5.1.6 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
                ('NombreModulo', models.CharField(max_length=100)),
                ('DescripcionModulo', models.TextField()),
            ],
        ),
    ]
