# Generated by Django 5.1.6 on 2025-03-13 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('TipoIdentificacion', models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('OT', 'Otro')], max_length=2, null=True)),
                ('NumeroIdentificacion', models.CharField(max_length=20, unique=True)),
                ('CiudadNacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('CorreoElectronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('ConfirmacionCorreo', models.EmailField(blank=True, max_length=254, null=True)),
                ('NumeroCelular', models.CharField(blank=True, max_length=15, null=True)),
                ('NumeroTelefonoAlternativo', models.CharField(blank=True, max_length=15, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('FechaNacimiento', models.DateField(blank=True, null=True)),
                ('DepartamentoResidencia', models.CharField(blank=True, max_length=100, null=True)),
                ('CiudadResidencia', models.CharField(blank=True, max_length=100, null=True)),
                ('DireccionResidencia', models.CharField(blank=True, max_length=200, null=True)),
                ('EntidadSalud', models.CharField(blank=True, max_length=100, null=True)),
                ('NombreColegio', models.CharField(blank=True, max_length=100, null=True)),
                ('EstamentoColegio', models.CharField(blank=True, choices=[('Publico', 'Público'), ('Privado', 'Privado')], max_length=10, null=True)),
                ('GradoEscolaridad', models.CharField(blank=True, max_length=50, null=True)),
                ('NombreAcudiente', models.CharField(blank=True, max_length=100, null=True)),
                ('NumeroCelularAcudiente', models.CharField(blank=True, max_length=15, null=True)),
                ('TieneDiscapacidad', models.BooleanField(blank=True, null=True)),
                ('TipoDiscapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('DescripcionDiscapacidad', models.TextField(blank=True, null=True)),
                ('TipoVinculacion', models.CharField(blank=True, choices=[('Particular', 'Particular'), ('Univalle', 'Relación Univalle')], max_length=15, null=True)),
                ('ValorConsignado', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('NumeroRecibo', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaConsignacion', models.DateField(blank=True, null=True)),
                ('NombreResponsablePago', models.CharField(blank=True, max_length=100, null=True)),
                ('TipoIdentificacionResponsablePago', models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('OT', 'Otro')], max_length=2, null=True)),
                ('NumeroIdentificacionResponsablePago', models.CharField(blank=True, max_length=20, null=True)),
                ('DireccionResidenciaResponsablePago', models.CharField(blank=True, max_length=200, null=True)),
                ('NumeroCelularResponsablePago', models.CharField(blank=True, max_length=15, null=True)),
                ('CorreoElectronicoResponsablePago', models.EmailField(blank=True, max_length=254, null=True)),
                ('DocumentoIdentidad', models.FileField(blank=True, null=True, upload_to='estudiantes/documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ReciboPago', models.FileField(blank=True, null=True, upload_to='estudiantes/documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ConstanciaEstudio', models.FileField(blank=True, null=True, upload_to='estudiantes/documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('password', models.CharField(default='1111', max_length=128)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('ModuloMatricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inscripciones', to='curse.modulo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
